import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useSharedState } from "src/pages/[user]";
import styles from "src/styles/Home.module.css";



const User: NextPage = () => {
  const { query } = useRouter();
  const [ retweet ] = useSharedState("retweet");
  const [name ,setName] = useState("");
  const [timer, setTimer] = useState<any>(undefined);
console.log(retweet);

const handleStart = ()=>{
    const intervalId = setInterval(()=>{
        const random = Math.floor(retweet.length*Math.random());
        console.log(retweet[random]);
        const name = retweet[random].name;
        const userName = retweet[random].username;
        setName(`${name}@${userName}`);
    },500);
    setTimer(intervalId);  
}
console.log(timer);


const handleStop = ()=>{
    const random = Math.floor(retweet.length * Math.random());
    const name = retweet[random].name;
    const userName = retweet[random].username;
    setName(`${name}@${userName}`);
    clearInterval(timer);
    setTimer(undefined);
}

  return (
    <div className={styles.container}>
      <Head>
        <title>ルーレット</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.box2}>{name}</div>

        <button onClick={handleStart} disabled={timer}>
          スタート！
        </button>

        <button onClick={handleStop} disabled={!timer}>
          ストップ！
        </button>
        <h1>リツイート一覧</h1>
        {retweet ? (
          retweet.map((item: any) => {
            return (
              <div key={`${item.id}${item.name}`}>
                <span>
                  {item.name}@{item.username}
                </span>
              </div>
            );
          })
        ) : (
          <div>No Data</div>
        )}
      </main>
    </div>
  );
};

export default User;
