import type { NextPage } from "next";
import Head from "next/head";
import styles from "src/styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ルーレット</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button
          onClick={async () => {
            const res = await fetch("api/hello");
            const json = await res.json();
            console.log(json);
            
          }}
        >
          ボタン
        </button>
      </main>
    </div>
  );
};

export default Home;
