import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";
import styles from "src/styles/Home.module.css";

type User = {
  description: string;
  id: string;
  name: string;
  profile_image_url: string;
  username: string;
};

const Home: NextPage = () => {
  const [name ,setName] = useState("");
  const { replace } = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>ルーレット</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/userNameExample.png"
          alt="ユーザー名の例"
          width={500}
          height={300}
        />
        <h1>ユーザー名を入れてください！</h1>
        <input
          type="text"
          onChange={(e) => {
            setName(e.target.value);
          }}
          value={name}
        />
        <button
          onClick={async () => {
            const trimName = name.trim();
            const res = await fetch(`api/getUser?userName=${trimName}`);
            const json = await res.json();
            await replace(`/${json.data.id}`);
          }}
        >
          ボタン
        </button>
      </main>
    </div>
  );
};

export default Home;
